### ISSUE TITLE
Create a server setup command

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid-rfh#68]
With Fabric
- [ ] Create a script that sets up an empty box that I can log in to with a username / password

Should do at least these things:

```
- name: Install packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes force=yes
  with_items:
      # Development tools
      - git

      # Python Dev
      - python-dev
      - python-setuptools
      - python-virtualenv

      # Just nice
      - screen
      - vim
      - emacs
      - htop
      - ack-grep
      - virtualenvwrapper
      - curl
      - tree

- name: Setup Working Directories
  sudo: yes
  file: path=/usr/lib/ohc state=directory mode=777
```
